FROM pytorch/torchserve:0.8.0-gpu

# copying requirements
COPY ./src/python/assistant/apps/torchserve/requirements.txt /usr/src/requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r /usr/src/requirements.txt
COPY ./src/python/assistant/apps/torchserve/build_script.py /usr/src/build_script.py
RUN python3 /usr/src/build_script.py

# copying model-store
COPY ./src/python/assistant/apps/torchserve/model_store /usr/src/model-store

# copying torchserve config
COPY ./src/python/assistant/apps/torchserve/torchserve.config /usr/src/torchserve.config